[2025-05-15T09:48:21.594+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: load_sales_csv.load_csv scheduled__2023-04-14T00:00:00+00:00 [queued]>
[2025-05-15T09:48:21.725+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: load_sales_csv.load_csv scheduled__2023-04-14T00:00:00+00:00 [queued]>
[2025-05-15T09:48:21.725+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T09:48:21.725+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-05-15T09:48:21.726+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T09:48:22.217+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_csv> on 2023-04-14 00:00:00+00:00
[2025-05-15T09:48:22.293+0000] {standard_task_runner.py:55} INFO - Started process 847 to run task
[2025-05-15T09:48:22.342+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'load_sales_csv', 'load_csv', 'scheduled__2023-04-14T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/load_sales.py', '--cfg-path', '/tmp/tmphz599d7_']
[2025-05-15T09:48:22.371+0000] {standard_task_runner.py:83} INFO - Job 105: Subtask load_csv
[2025-05-15T09:48:22.907+0000] {task_command.py:389} INFO - Running <TaskInstance: load_sales_csv.load_csv scheduled__2023-04-14T00:00:00+00:00 [running]> on host 1430ca430efd
[2025-05-15T09:48:25.036+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_sales_csv
AIRFLOW_CTX_TASK_ID=load_csv
AIRFLOW_CTX_EXECUTION_DATE=2023-04-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-14T00:00:00+00:00
[2025-05-15T09:48:39.897+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-15T09:48:40.361+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_sales.py", line 10, in load_csv_to_postgres
    df.to_sql('raw_sales', engine, if_exists='replace', index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2882, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 728, in to_sql
    **engine_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1770, in to_sql
    **engine_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1340, in insert_records
    table.insert(chunksize=chunksize, method=method)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 967, in insert
    exec_insert(conn, keys, chunk_iter)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 881, in _execute_insert
    data = [dict(zip(keys, row)) for row in data_iter]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 881, in <listcomp>
    data = [dict(zip(keys, row)) for row in data_iter]
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-05-15T09:48:40.400+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=load_sales_csv, task_id=load_csv, execution_date=20230414T000000, start_date=20250515T094821, end_date=20250515T094840
[2025-05-15T09:48:40.714+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 105 for task load_csv (Task received SIGTERM signal; 847)
[2025-05-15T09:48:40.856+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T09:48:40.980+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
